# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('bear_type', models.CharField(choices=[('grizzy', 'Grizzy'), ('mini', 'Mini')], max_length=128, verbose_name='Name')),
            ],
        ),
    ]
